build:
  test:
    image: tannv85/maven3.9-jdk8
    volumes:
      - target:/opt/tomcat/webapps
    commands:
      - mvn surefire-report:report
      - framgia-ci run
    when:
      event: [push, tag, pull_request]

# compose:
#   database:
#     image: mysql
#     expose:
#       - "3306"
#     environment:
#       MYSQL_DATABASE: demo_db
#       MYSQL_USER: demo_user
#       MYSQL_PASSWORD: demo_pw
#       MYSQL_ROOT_PASSWORD: root

cache:
  mount:
    - .git
    - /drone/.m2

debug: true