project_type: java
test:
 mvn:
   ignore: true
   command:
#    - mvn clean surefire-report:report -X
    - mvn surefire-report:report -DoutputDirectory=.framgia-ci-reports/surefire
#    - cp target/site/tools.html .framgia-ci-reports/tools.html